files:
  - source: /Resources/Private/Language/**/locallang*.xlf
    ignore:
      - /Resources/Private/Language/**/%two_letters_code%.%original_file_name%
    translation: /Resources/Private/Language/**/%two_letters_code%.%original_file_name%
